### ISSUE TITLE
1.12 odd crash

### ISSUE THREAD

**Issue by Zygus42** [LothrazarMinecraftMods/OceanFloorControl#3]
OceanFloor-1.12-1.0.1
forge-1.12.2-14.23.3.2673-installer-win

It seems fine when I leave the config as is, but I don't just want a few small patches of clay and sand, but want a lot of sand in the oceans.  So I changed the config to:

    I:clay_chance=65
    I:clay_size=32
    I:dirt_chance=30
    I:dirt_size=18
    I:sand_chance=85
    I:sand_size=200

And it's crashing:
[crash-2018-05-10_11.41.12-server.txt](https://github.com/PrinceOfAmber/OceanFloorControl/files/1990470/crash-2018-05-10_11.41.12-server.txt)

**Comment by Zygus42** [comment]
Revisiting this and it's still crashing if I push the numbers too high.
    I:sand_chance=128
    I:sand_size=128

[crash-2019-02-28_17.56.44-server.txt](https://github.com/Lothrazar/OceanFloorControl/files/2914435/crash-2019-02-28_17.56.44-server.txt)

**Comment by Lothrazar** [comment]
Hey sorry i never checked this issue tracker ill be more frequent.  i never fixed it since because theres no one number that is a hard limit, just if its "too big" then some chunks sometimes overflow.

If size 32 crashes for some people then it wont crash for others so i kinda got stuck and walked away.  1.14 will be a whole new world though
